version: '3.9'
services:
  lumo-emulator:
    build: .
    privileged: true
    volumes:
      - "./scripts:/build/scripts:ro"
      - "./work:/build/work"
      - "../lumo_image_builder/output_image:/build/output:ro"
      - "/dev:/dev"
    ports:
      - "8080:8080"
      - "8443:8443"
    working_dir: /build
    entrypoint: []
    command: >
      bash -lc "set -e; mkdir -p /build/work; bash /build/scripts/run-raspi-emulator.sh"
    restart: "no"
